/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,ts}',
    './archive.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Theme-aware: defined as CSS variables so light/dark both work with opacity modifiers
        'primary':                    'rgb(var(--color-primary) / <alpha-value>)',
        'on-primary':                 'rgb(var(--color-on-primary) / <alpha-value>)',
        'primary-container':          'rgb(var(--color-primary-container) / <alpha-value>)',
        'on-primary-container':       'rgb(var(--color-on-primary-container) / <alpha-value>)',
        'background':                 'rgb(var(--color-background) / <alpha-value>)',
        'on-background':              'rgb(var(--color-on-background) / <alpha-value>)',
        'surface':                    'rgb(var(--color-surface) / <alpha-value>)',
        'surface-dim':                'rgb(var(--color-surface-dim) / <alpha-value>)',
        'surface-bright':             'rgb(var(--color-surface-bright) / <alpha-value>)',
        'surface-variant':            'rgb(var(--color-surface-variant) / <alpha-value>)',
        'surface-container':          'rgb(var(--color-surface-container) / <alpha-value>)',
        'surface-container-low':      'rgb(var(--color-surface-container-low) / <alpha-value>)',
        'surface-container-high':     'rgb(var(--color-surface-container-high) / <alpha-value>)',
        'surface-container-highest':  'rgb(var(--color-surface-container-highest) / <alpha-value>)',
        'surface-container-lowest':   'rgb(var(--color-surface-container-lowest) / <alpha-value>)',
        'on-surface':                 'rgb(var(--color-on-surface) / <alpha-value>)',
        'on-surface-variant':         'rgb(var(--color-on-surface-variant) / <alpha-value>)',
        'outline':                    'rgb(var(--color-outline) / <alpha-value>)',
        'outline-variant':            'rgb(var(--color-outline-variant) / <alpha-value>)',
        'inverse-primary':            'rgb(var(--color-inverse-primary) / <alpha-value>)',
        'inverse-surface':            'rgb(var(--color-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':         'rgb(var(--color-inverse-on-surface) / <alpha-value>)',
        // Static: accent/badge/error/fixed colours that don't change with theme
        'tertiary-fixed-dim':         '#ffba38',
        'secondary-fixed-dim':        '#ffb3b2',
        'primary-fixed-dim':          '#95ccff',
        'secondary-fixed':            '#ffdad9',
        'on-tertiary-container':      '#573b00',
        'on-error':                   '#690005',
        'error':                      '#ffb4ab',
        'on-tertiary-fixed-variant':  '#604100',
        'tertiary-fixed':             '#ffdeac',
        'on-tertiary':                '#432c00',
        'tertiary':                   '#ffbb3d',
        'on-error-container':         '#ffdad6',
        'on-tertiary-fixed':          '#281900',
        'on-primary-fixed':           '#001d32',
        'primary-fixed':              '#cde5ff',
        'secondary-container':        '#9f0224',
        'tertiary-container':         '#e39f00',
        'secondary':                  '#ffb3b2',
        'on-secondary':               '#680014',
        'on-secondary-container':     '#ffa8a8',
        'on-secondary-fixed':         '#410009',
        'on-secondary-fixed-variant': '#920020',
        'secondary-container-fixed':  '#ffdad9',
        'surface-tint':               '#95ccff',
        'error-container':            '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Plus Jakarta Sans'],
        label: ['Space Grotesk'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
