/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,ts}',
    './archive.html',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffba38',
        'secondary-fixed-dim': '#ffb3b2',
        'primary-fixed-dim': '#95ccff',
        'surface': '#101418',
        'surface-dim': '#101418',
        'surface-bright': '#36393f',
        'on-background': '#e0e2e9',
        'secondary-fixed': '#ffdad9',
        'on-tertiary-container': '#573b00',
        'on-error': '#690005',
        'background': '#101418',
        'inverse-primary': '#00639a',
        'error': '#ffb4ab',
        'on-tertiary-fixed-variant': '#604100',
        'secondary-container': '#9f0224',
        'tertiary-fixed': '#ffdeac',
        'surface-variant': '#31353a',
        'on-tertiary': '#432c00',
        'surface-container': '#1c2025',
        'tertiary': '#ffbb3d',
        'surface-container-highest': '#31353a',
        'outline': '#8a919b',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed': '#281900',
        'on-primary-fixed': '#001d32',
        'primary-fixed': '#cde5ff',
        'on-surface-variant': '#c0c7d1',
        'tertiary-container': '#e39f00',
        'outline-variant': '#404750',
        'surface-container-high': '#262a2f',
        'secondary': '#ffb3b2',
        'primary-container': '#66b2f2',
        'on-primary': '#003352',
        'inverse-on-surface': '#2d3136',
        'error-container': '#93000a',
        'on-secondary-fixed-variant': '#920020',
        'on-secondary-fixed': '#410009',
        'surface-container-low': '#181c21',
        'surface-container-lowest': '#0a0f13',
        'primary': '#97ccff',
        'inverse-surface': '#e0e2e9',
        'on-primary-fixed-variant': '#004a75',
        'surface-tint': '#95ccff',
        'on-secondary-container': '#ffa8a8',
        'on-secondary': '#680014',
        'on-surface': '#e0e2e9',
        'on-primary-container': '#00436a',
        'secondary-container-fixed': '#ffdad9',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Space Grotesk'],
        body: ['Plus Jakarta Sans'],
        label: ['Space Grotesk'],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
};
